# generated by datamodel-codegen:
#   filename:  <stdin>

from typing import TypedDict


class CodeReferenceSubmit(TypedDict):
    file_path: str
    line_number: int
    feature_name: str


class FeatureFlagCodeReferencesScan(TypedDict):
    created_at: str
    repository_url: str
    project: int
    revision: str
    code_references: list[CodeReferenceSubmit]
