# generated by datamodel-codegen:
#   filename:  <stdin>

from typing import NotRequired, TypedDict


class CodeReferenceSubmit(TypedDict):
    file_path: str
    line_number: int
    feature_name: str


class FeatureFlagCodeReferencesScan(TypedDict):
    created_at: NotRequired[str]
    repository_url: str
    project: NotRequired[int]
    revision: str
    code_references: list[CodeReferenceSubmit]
    vcs_provider: NotRequired[str]
