name: Collect code references
permissions:
  contents: read  # Required for actions/checkout to clone the repository

on:
  workflow_call:

    inputs:

      flagsmith_project_id:
        type: number
        description: Flagsmith project ID
        required: true

      flagsmith_admin_api_url:
        type: string
        description: Flagsmith admin API URL
        default: https://api.flagsmith.com

      exclude_patterns:
        type: string
        description: Comma-separated list of patterns to exclude from scanning
        default: ''

    secrets:

      flagsmith_admin_api_key:
        description: Flagsmith admin API key
        required: true

jobs:
  fetch:
    name: Fetch feature names
    runs-on: ubuntu-latest
    outputs:
      feature_names: ${{ steps.fetch.outputs.feature_names }}
    steps:
      - name: Fetch feature names
        id: fetch
        uses: Flagsmith/ci/fetch-feature-names@feat/github-code-references-reusable-workflow
        with:
          flagsmith_project_id: ${{ inputs.flagsmith_project_id }}
          flagsmith_admin_api_url: ${{ inputs.flagsmith_admin_api_url }}
          flagsmith_admin_api_key: ${{ secrets.flagsmith_admin_api_key }}

  scan:
    name: Scan codebase
    runs-on: ubuntu-latest
    needs: fetch
    outputs:
      code_references: ${{ steps.collect.outputs.code_references }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Collect code references
        id: collect
        uses: Flagsmith/ci/collect-code-references@feat/github-code-references-reusable-workflow
        with:
          feature_names: ${{ needs.fetch.outputs.feature_names }}
          exclude_patterns: ${{ inputs.exclude_patterns }}

  upload:
    name: Upload results
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Upload code references
        uses: Flagsmith/ci/upload-code-references@feat/github-code-references-reusable-workflow
        with:
          code_references: ${{ needs.scan.outputs.code_references }}
          flagsmith_project_id: ${{ inputs.flagsmith_project_id }}
          flagsmith_admin_api_url: ${{ inputs.flagsmith_admin_api_url }}
          flagsmith_admin_api_key: ${{ secrets.flagsmith_admin_api_key }}
          repository_url: ${{ github.server_url }}/${{ github.repository }}
          revision: ${{ github.sha }}
